<?php
// module/Album/view/album/album/add.phtml:
$title = 'Edit profile';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('user', array('action' => 'editprofile')));
$form->prepare();
echo $this->form()->openTag($form);
echo $this->formRow($form->get('username'));
echo $this->formRow($form->get('newpassword'));
echo $this->formRow($form->get('name'));
echo $this->formRow($form->get('email'));
echo $this->formRow($form->get('id'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();