<div class="nav-collapse collapse">
	<ul class="nav1">
		<li class="active first"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
		<li class="active"><a href="<?php echo $this->url('album') ?>"><?php echo $this->translate('Album') ?></a></li>
		<?php if(isset($this->username) && $this->username != '') :?>
		<li class="active"><a href="<?php echo $this->url('user',array('action'=>'logout')) ?>"><?php echo $this->translate('Logout') ?></a></li>	
		<?php else:?>
		<li class="active"><a href="<?php echo $this->url('user',array('action'=>'login')) ?>"><?php echo $this->translate('Login') ?></a></li>
		<li class="active"><a href="<?php echo $this->url('user',array('action'=>'register')) ?>"><?php echo $this->translate('Register') ?></a></li>
		<?php endif; ?>
		<li class="active"><a href="<?php echo $this->url('contact',array('action'=>'index')) ?>"><?php echo $this->translate('Contact Us') ?></a></li>
	</ul>
</div><!--/.nav-collapse -->
<div class="clear"></div>
<?php if(isset($this->username) && $this->username != '') :?> 
		<div class="userinfo"><strong>Welcome</strong> <?php echo '<u>'.$this->username.'</u>!';?></div> 
<?php endif;?>
<div class="clear"></div>
<div class="hero-unit">
    <h1><?php echo sprintf($this->translate('Welcome to %sMy Zend Project%s'), '<span class="zf-green">', '</span>') ?></h1>
    <p></p>
</div>

<div class="row">

    <div class="span4">
        <h4><?php echo $this->translate('Login') ?></h4> <a href="<?php echo $this->basePath(); ?>/user/login">Click here >></a>
        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
    </div>

    <div class="span4">
        <h4><?php echo $this->translate('Album') ?></h4> <a href="<?php echo $this->basePath(); ?>/album">Click here >></a>
        <p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>
   </div>

   <div class="span4">
       <h4><?php echo $this->translate('Registration') ?></h4> <a href="<?php echo $this->basePath(); ?>/user/register">Click here >></a>
       <p>standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
   </div>
</div>
